# Python Programming language:Functions

In [1]:
x = 1
y = 2
x + y

3

In [2]:
x

1

Function for adding two numbers

In [5]:
def add_num(x,y):
    return x+y

add_num(2,3)

5

Function for adding three numbers

In [6]:
def add_num(x,y,z):
    return x+y+z

add_num(4,3,1)

8

optional parameter in functions:

In [7]:
def add_num(x,y,z=None):
    if(z==None):
        return x+y
    else:
        return x+y+z

add_num(1,2)

3

assigning a function to a variable

In [12]:
a=add_num
a(1,2,3)

6

# The Python Programming Language: Types and Sequences

 obtaining the type of variable using type inbuilt function

In [14]:
type('sai')

str

In [15]:
type(x)

int

In [16]:
type(add_num)

function

In [17]:
type(1.0)

float

tuple is a sequence of variables which itself is a immutable

In [19]:
tpl=(1,'a',3,'g')
type(tpl)

tuple

In [20]:
tpl

(1, 'a', 3, 'g')

Lists in python are similar to python tuple with the exception that they are mutable

In [25]:
l=[1,'a',3,'g']
type(l)

list

In [26]:
l

[1, 'a', 3, 'g']

We can add new items to the end of the list by append function

In [27]:
l.append(4)
l

[1, 'a', 3, 'g', 4]

In [28]:
for item in l:
    print(item)

1
a
3
g
4


accessing by indexing

In [29]:
l[0]

1

In [30]:
l[-1] #returns the last element in the list

4

In [31]:
l[1:4] #slicing over a list

['a', 3, 'g']

In [32]:
[1,2] + [3,4] #concatinate the two lists 

[1, 2, 3, 4]

In [33]:
2 in l # checks whether the element is present in list or not

False

In [34]:
s='Yahoo! I am learning applied data science with python by Michigan University'

type(s)

s[3:5] #Each and every string in python is a list of characters. So slicing works wonderfully


'oo'

In [36]:
firstname = 'sai'
lastname = 'kumar'

print(firstname + ' ' + lastname) # concatination of two strings

print(firstname * 2) #Repetation of firstname 2 times

print('a' in firstname)

sai kumar
saisai
True


In [37]:
s.split(' ')[0] #splitting the string using split function based in pattern and selecting the word at 0 index

'Yahoo!'

Dictionaries in python

In [38]:
di={'sai':'nagubandisai40@gmail.com','sri latha':'lathasri0@gmail.com'}

type(di)

di['sai']

'nagubandisai40@gmail.com'

In [39]:
for name in di:
    print(di[name])

nagubandisai40@gmail.com
lathasri0@gmail.com


In [40]:
for keys,values in di.items():
    print(keys)
    print(values)

sai
nagubandisai40@gmail.com
sri latha
lathasri0@gmail.com


In [41]:
for value in di.values():
    print(value)

nagubandisai40@gmail.com
lathasri0@gmail.com


In [45]:
x=(2,3,1)
a,b,c=x #unpacking the sequence into different variables

print(a,b,c) #Make sure that the number of variables in leftside and the elements present in the list should be same

2 3 1


# Python programming language: More on Strings

In [47]:
s='sai'+ 2 # we need to type cast an object to str before performing addition

TypeError: can only concatenate str (not "int") to str

In [49]:
s = 'sai' + str(2)
print(s)

sai2


In [4]:
#String formatting
s={'mail':'nagubandisai40@gmail.com','name':'Sai Kumar'}
st='{} is a person with mailId {}'
print(st.format(s['name'],s['mail']))

Sai Kumar is a person with mailId nagubandisai40@gmail.com


# Python Demonstration: Reading and Writing into csv files

In [33]:
import csv

%precision 2

with open('african_crises.csv') as csvfile:
    mpg=list(csv.DictReader(csvfile))
    
mpg[:3]

[OrderedDict([('case', '1'),
              ('cc3', 'DZA'),
              ('country', 'Algeria'),
              ('year', '1870'),
              ('systemic_crisis', '1'),
              ('exch_usd', '0.052264'),
              ('domestic_debt_in_default', '0'),
              ('sovereign_external_debt_default', '0'),
              ('gdp_weighted_default', '0'),
              ('inflation_annual_cpi', '3.441455696'),
              ('independence', '0'),
              ('currency_crises', '0'),
              ('inflation_crises', '0'),
              ('banking_crisis', 'crisis')]),
 OrderedDict([('case', '1'),
              ('cc3', 'DZA'),
              ('country', 'Algeria'),
              ('year', '1871'),
              ('systemic_crisis', '0'),
              ('exch_usd', '0.052798'),
              ('domestic_debt_in_default', '0'),
              ('sovereign_external_debt_default', '0'),
              ('gdp_weighted_default', '0'),
              ('inflation_annual_cpi', '14.14913958'),
        

In [34]:
mpg[0].keys() #for getting all the column names

odict_keys(['case', 'cc3', 'country', 'year', 'systemic_crisis', 'exch_usd', 'domestic_debt_in_default', 'sovereign_external_debt_default', 'gdp_weighted_default', 'inflation_annual_cpi', 'independence', 'currency_crises', 'inflation_crises', 'banking_crisis'])

In [35]:
len(mpg) #Number of rows present in the csv file

1059

In [36]:

sum(float(d['inflation_crises']) for d in mpg)
    

137.00

In [37]:
case=set(d['case'] for d in mpg)
case

{'1', '10', '15', '19', '2', '35', '38', '40', '45', '56', '63', '69', '70'}

In [52]:
ls=[]

for c in case:
    s=0
    cnt=0
    for d in mpg:
        if d['case']==str(c):
            s=s+float(d['case'])
            cnt=cnt+1
    ls.append((c,s))

print(ls)

[('15', 945.0), ('70', 6300.0), ('38', 2584.0), ('45', 2700.0), ('69', 4968.0), ('19', 2945.0), ('1', 85.0), ('35', 2345.0), ('56', 6384.0), ('10', 580.0), ('2', 154.0), ('40', 3000.0), ('63', 4725.0)]


As it looks somewhat inefficient don't worry we will learn pandas which will be easy to manipulate the data.

# Pyhton Dates and times

In [53]:
import datetime as dt

import time as tm

In [54]:
tm.time() #creates the time stamp

1574834632.59

In [57]:
dtnow=dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2019, 11, 27, 11, 35, 0, 358872)

In [59]:
print(dtnow.year , dtnow.month , dtnow.day) #Different attributes to access date,day,time etc

2019 11 27


In [75]:
delta=dt.timedelta(100) #creating a time delta for 100 days
delta

datetime.timedelta(days=100)

In [70]:
today=dt.date.today()


In [76]:
today-delta #performing various operations using delta such as getting 100 days before date 

datetime.date(2019, 8, 19)

In [77]:
today+delta

datetime.date(2020, 3, 6)

In [78]:
today>today-delta

True

# The python programming language: Objects and map()

In [80]:
class Person:
    department='IT' #class Variable
    
    def set_name(self, new_name): # Declaring methods inside the class 
        self.name=new_name
    def set_mail(self,new_mail):
        self.mail=new_mail

In [88]:
p=Person() #Creating a object for the Person class and we can define the constructor using __init__ in python

In [89]:
# We cannot have any private or public modifiers in python if you instantiate an object you have a full access

map(function,iterator..) which returns the iterator after applying the function to every item in the iterable

In [94]:
store1=[1,55,63,34]
store2=[4,6,33,21]
result=map(min,store1,store2)
list(result)

[1, 6, 33, 21]

# Advanced Python: lambda and list Comprehensions

lambda is used to create an anonymous functions in python.This are same as the other functions but with no-name

In [97]:
my_func = lambda a,b,c : a+b #parameters followed by colon and the single expression

In [98]:
my_func(1,2,3)

3

In [104]:
my_list=[]
for x in range(1000):
    if(x%2==0):
        my_list.append(x)
    
print(my_list)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206, 208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232, 234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258, 260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284, 286, 288, 290, 292, 294, 296, 298, 300, 302, 304, 306, 308, 310, 312, 314, 316, 318, 320, 322, 324, 326, 328, 330, 332, 334, 336, 338, 340, 342, 344, 346, 348, 350, 352, 354, 356, 358, 360, 362, 364, 366, 368, 370, 372, 374, 376, 378, 380, 382, 384, 386, 388, 390, 392, 394, 396, 398, 400, 402, 404, 406, 408, 410, 412, 414, 416, 418, 420,

In [103]:
my_list=[x for x in range(1000) if x%2==0]
my_list

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

# Numpy module:

In [105]:
import numpy as np #numpy is a module which is mostly used in datascience 

# Creating arrays

In [108]:
my_list=[1,2,3]

x=np.array(my_list)

x

array([1, 2, 3])

In [110]:
y=np.array([1,2,3])
y

array([1, 2, 3])

In [114]:
m=np.array([[1,2,3],[4,5,6]])
print(m)


[[1 2 3]
 [4 5 6]]


In [115]:
m.shape

(2, 3)

In [117]:
n=np.arange(0,20,2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [118]:
n.reshape((2,5))

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [121]:
o=np.linspace(0,20,9)
o

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. ])

In [125]:
o.resize((3,3))
o

array([[ 0. ,  2.5,  5. ],
       [ 7.5, 10. , 12.5],
       [15. , 17.5, 20. ]])

In [126]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [128]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [131]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [132]:
np.array([1,2,3]*3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [133]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [139]:
p=np.ones((2,3),dtype='int')
p

array([[1, 1, 1],
       [1, 1, 1]])

In [140]:
np.vstack((p,p*2))

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [141]:
np.hstack((p,p*2))

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

# Operations on numpy array

In [142]:
x

array([1, 2, 3])

In [143]:
y

array([1, 2, 3])

In [144]:
x+y

array([2, 4, 6])

In [145]:
x*y

array([1, 4, 9])

In [146]:
x-y

array([0, 0, 0])

In [147]:
x**2

array([1, 4, 9], dtype=int32)

In [148]:
x.dot(y)

14

In [154]:
z=np.random.randint(0,100,(3,2))
z.shape

(3, 2)

In [155]:
z.T #Transpose of the array

array([[17, 39, 60],
       [18, 81, 88]])

In [156]:
z.shape

(3, 2)

In [157]:
z.dtype

dtype('int32')

In [158]:
z.astype('f')

array([[17., 18.],
       [39., 81.],
       [60., 88.]], dtype=float32)

In [159]:
a=np.array([2,1,4,6,-1,-4])

In [160]:
a.sum()

8

In [161]:
a.min()

-4

In [162]:
a.max()

6

In [163]:
a.std()

3.2489314482696545

In [164]:
a.mean()

1.3333333333333333

In [167]:
a.argmax() #returns the index of max number in  the array

3

In [168]:
a.argmin() #returns the min number index in the array

5

# Indexing or Slicing

In [170]:
s=np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144],
      dtype=int32)

In [171]:
s[0]

0

In [172]:
s[3:]

array([  9,  16,  25,  36,  49,  64,  81, 100, 121, 144], dtype=int32)

In [173]:
s[-1]

144

In [175]:
s[-4:-1]

array([ 81, 100, 121], dtype=int32)

In [177]:
s[-5::-2]

array([64, 36, 16,  4,  0], dtype=int32)

In [179]:
r=np.arange(36)
r.resize((6,6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [185]:
r[2,2] #Getting the value at second row second column

14

In [183]:
r[3,3:]

array([21, 22, 23])

In [184]:
r[:2,:-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [186]:
r>10 #retuen the boolean array known as boolean mask

array([[False, False, False, False, False, False],
       [False, False, False, False, False,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [188]:
r[r>10] #get all the elements which satisfy the condition

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35])

In [189]:
r[r>30]=30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [191]:
r2=r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [193]:
r2[0,0]=99
r2

array([[99,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [195]:
r # the element at 0 row and 0 column was also changed in this array

array([[99,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [197]:
r2=r[3:,3:].copy()
r2

array([[21, 22, 23],
       [27, 28, 29],
       [30, 30, 30]])

In [198]:
r2[0,0]=100
r2

array([[100,  22,  23],
       [ 27,  28,  29],
       [ 30,  30,  30]])

In [201]:
r # To avoid the above problem we use copy method

array([[99,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

# Iterating Over Arrays

In [202]:
test = np.random.randint(0,100,(4,3))
test

array([[38, 77, 85],
       [ 6, 66, 62],
       [62, 40, 71],
       [84, 66, 62]])

In [203]:
for row in test:
    print(row)

[38 77 85]
[ 6 66 62]
[62 40 71]
[84 66 62]


In [205]:
for i in range(len(test)):
    print(test[i])

[38 77 85]
[ 6 66 62]
[62 40 71]
[84 66 62]


In [206]:
for i,row in enumerate(test):
    print('row ',i,'is ',row)

row  0 is  [38 77 85]
row  1 is  [ 6 66 62]
row  2 is  [62 40 71]
row  3 is  [84 66 62]


In [207]:
test2=test**2
test2

array([[1444, 5929, 7225],
       [  36, 4356, 3844],
       [3844, 1600, 5041],
       [7056, 4356, 3844]], dtype=int32)

In [209]:
for i,j in zip(test,test2):
    print(i,' + ',j,' = ',i+j)

[38 77 85]  +  [1444 5929 7225]  =  [1482 6006 7310]
[ 6 66 62]  +  [  36 4356 3844]  =  [  42 4422 3906]
[62 40 71]  +  [3844 1600 5041]  =  [3906 1640 5112]
[84 66 62]  +  [7056 4356 3844]  =  [7140 4422 3906]
